package protocol;

public enum ProtocolMessageType {
    LOGIN,
    SIGNUP,
    AUTH_RESPONSE,

    PUBLIC_MESSAGE,
    PRIVATE_MESSAGE,
    ROOM_MESSAGE,

    USERS_REQUEST,
    USERS_RESPONSE,

    HISTORY_RESPONSE,
    SYSTEM_MESSAGE,

    CREATE_ROOM,
    JOIN_ROOM,
    LEAVE_ROOM,
    ROOM_LIST_REQUEST,
    ROOM_LIST_RESPONSE,
    ROOM_MEMBERS_REQUEST,
    ROOM_MEMBERS_RESPONSE,

    TYPING,
    STOP_TYPING,
    PRESENCE_UPDATE,

    DISCONNECT
}